- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        name: "resource_group_east_us_2"
        location: "eastus2"
        state: absent